apiVersion: v1
kind: Service
metadata:
  name: healthetile-service
  labels:
    app: healthetile
spec:
  type: LoadBalancer
  selector:
    app: healthetile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
